[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "node network/node.js --port $PORT --api 7001 --mine"
  healthcheckPath = "/"
  healthcheckTimeout = 30

[[services]]
  protocol = "tcp"
  internalPort = 6001

[[services]]
  protocol = "tcp"  
  internalPort = 7001
